name: Upload Debug APK to GitHub

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      isCI: "true"
      API_URL: ${{ secrets.API_URL }}
      BASE_SCHEME: ${{ secrets.BASE_SCHEME }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: |
          echo "BASE_URL=${API_URL}" >> local.properties
          echo "BASE_SCHEME=${BASE_SCHEME}" >> local.properties

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Releasing using Hub
        uses: kyze8439690/action-release-releaseapk@1.0.0
        env:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}
         APP_FOLDER: app
