name: Upload Debug APK to GitHub on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  apk:
      runs-on: ubuntu-latest

      env:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}
         isCI: "true"
         API_URL: ${{ secrets.API_URL }}
         BASE_SCHEME: ${{ secrets.BASE_SCHEME }}
      
      steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: |
          echo "BASE_URL=${API_URL}" >> local.properties
          echo "BASE_SCHEME=${BASE_SCHEME}" >> local.properties
        
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
        
      - name: Upload APK to Github Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          release_name: "Debug ${{github.ref_name}}"
          draft: false
          prerelease: false

      - name: Upload APK to Release
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./app/build/outputs/apk/debug/app-debug.apk
          asset_name: app-debug.apk
          asset_content_type: application/zip
