name: Build and test

on:
  pull_request:
    branches:
      - 'asasas*'
      
jobs:
  android_test:
    name: Android - Test
    runs-on: ubuntu-22.04
    env:
      isCI: "true"
      BASE_URL: https://testapi.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: "17"

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3

      - name: Add current platform to Bundler lockfile
        run: |
          bundle lock --add-platform ruby
          bundle lock --add-platform x86_64-linux
          
      - name: Install Gems
        run: bundle install

      - name: Run Tests
        run: bundle exec fastlane test
        env:
          BASE_URL: ${{ secrets.BASE_URL_DEBUG }}
          BASE_SCHEME: ${{ secrets.BASE_SCHEME_DEBUG }}
