name: Upload Debug APK to GitHub

on:
  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      isCI: "true"
      API_URL: ${{ secrets.API_URL }}
      BASE_SCHEME: ${{ secrets.BASE_SCHEME }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: |
          echo "BASE_URL=${API_URL}" >> local.properties
          echo "BASE_SCHEME=${BASE_SCHEME}" >> local.properties

      - name: Build gradle project
        run: ./gradlew build --stacktrace

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk