name: Build and test

on:
  pull_request:
    branches:
      - main
      
jobs:
  android_build_and_test:
    name: Android - build and test
    runs-on: ubuntu-22.04
    env:
      isCI: "true"
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: '17'
      - name: Build android 
        run: ./gradlew assembleDebug testDebug
